spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update # TODO: 나중에 none으로 수정 필요
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

app:
  lock:
    wait-timeout-ms: 3000
    lease-timeout-ms: 5000
    retry-interval-ms: 50
  data-platform:
    base-url:
  outbox:
    max-retry-count: 3
  kafka:
    enabled: false
    topic:
      reservation-payment: reservation.payment.completed
    consumer-group: hhplus-reservation-data-platform

---
spring.config.activate.on-profile: kafka

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

app:
  kafka:
    enabled: true
